- package.json
It seems to taiwanese url.:sweat_smile:
> Fix repo's url on package.json

- exercises/baby_steps/problem.pt-br.md
- exercises/filtered_ls/problem.pt-br.md
- exercises/hello_world/problem.pt-br.md
- exercises/http_client/problem.pt-br.md
- exercises/http_collect/problem.pt-br.md
- exercises/http_file_server/problem.pt-br.md
- exercises/http_json_api_server/problem.pt-br.md
- exercises/http_uppercaserer/problem.pt-br.md
- exercises/juggling_async/problem.pt-br.md
- exercises/make_it_modular/problem.pt-br.md
- exercises/my_first_async_io/problem-pt-br.md
- exercises/my_first_io/problem.pt-br.md
- exercises/time_server/problem.pt-br.md
- i18n/credits/pt-br.txt
- i18n/help/pt-br.txt
- i18n/pt-br.json
- learnyounode.js
Hello, we have done a brazilian portuguese translation, we hope you like it.
In case you want to see more details about our work, this is the link to our repository https://github.com/lucasfcosta/learnyounode-pt-br
> Adding pt-br translation files

- README.md
- credits.txt
Well, it seems like I'm the only one without a twitter account, can I leave it this way or should I add another link to replace it?
> updating collaborators

- README.md
- package.json
> Adding Martin Heidegger to the collaborators lists.

- package.json
Sorry for all these pull requests, I just thought it would be easier to fix this if I just did it again after pulling from the upstream/master.
I will make sure to study about git's rebase tool as soon as I get home.
> Updating collaborators on package.json

- exercises/my_first_io/solution_ja/solution.js
> Update Japanese Message on My_First_Io

- README.md
- package.json
Squashed into a single commit.
> added my contact info in the readme and package.json

- exercises/my_first_io/problem.fr.md
As per request from @rvagg, added translation for tiny extra wording in My First I/O problem.
> L10n fr: added new wording from master in My First I/O.

- exercises/my_first_io/problem.es.md
> minor fixes on spanish translation

- exercises/my_first_io/problem.es.md
- exercises/my_first_io/problem.fr.md
- exercises/my_first_io/problem.md
- exercises/my_first_io/problem.pt-br.md
Some people get confused and think it is the number of lines instead of
new lines, adding (\n) to remove confusion
> specify newlines (\n)

- i18n/fr.json
> L10n fr: added translations for dont_use_dot keys

- exercises/hello_world/solution_pt-br/solution.js
The "Hello World" exercise ask to the student to create a file and print to stdout the phrase "Olá, Mundo" in portuguese.
The missing of this file forces the user to have to print "Hello World" in English to pass to the next exercise.
> Hello World solution for PT-BR

- i18n/ko.json
Sorry, #276 was missing menus.  :bow:
> Add menu translation to Korean

- exercises/http_json_api_server/exercise.js
relate #295 
We need different error message when header is wrong. but, I don't know how to check header.
> Fix TypeError

- exercises/my_first_async_io/solution_es/solution.js
> Update Spanish message

- README.md
- credits.txt
Just small tweak of the representation of my name. Thanks!
> Update capitalization of the name

- i18n/zh-cn.json
> add dont_use_dot msg

- exercises/hello_world/problem.md
`,` instead of `.` ahead of e.g.
> Punctuation

- exercises/http_collect/problem.pt-br.md
Adding a word in the sentence at http_collect/problem.pt-br.md file. :smile:
> Adding a word in the sentence

- i18n/pt-br.json
I'm sorry it took so long for me to see this issue.
Please let me know if you need any other things related to the pt-br translation.
> Translation for dont_use_dot. Related to #328

- i18n/fr.json
A little correction in the french translation.
> Wording i18n/fr.json

- exercises/my_first_async_io/problem.fr.md
A little correction in the french translation.
> Wording exercises/my_first_async_io/problem.fr.md

- exercises/filtered_ls/problem.md
Ran into an issue with a misunderstanding of what was meant by "the first argument to your program", they thinking that the first argument is the first value of `process.argv`. This clarification is designed to alleviate that misunderstanding.
> Clarify what "first" is when referring to args

- exercises/hello_world/problem.pt-br.md
- exercises/http_client/problem.pt-br.md
- exercises/http_collect/problem.pt-br.md
- exercises/http_file_server/problem.pt-br.md
- exercises/make_it_modular/problem.pt-br.md
- exercises/my_first_io/problem.pt-br.md
- exercises/time_server/problem.pt-br.md
To maintain compliance with other languages. Do not translate program.js name file.
> Fix typo in hello_world pt-br resource

- exercises/http_client/solution/solution.js
'error' event is emitted on the returned request object, not on response object
> Fix 'error' event source

- README.md
I had some problems when running step 3 `learnyounode`, it didn't work. It had no output errror, so I fixed running 'sudo apt-get install nodejs-legacy'.
> Updating env steps in readme

- exercises/make_it_modular/verify.js
- test/make_it_modular/invalid_15.js
- test/make_it_modular/module_invalid_15.js
This PR fixes the bug reported in #432
> Fixes unchecked error in make it modular

- exercises/http_uppercaserer/solution/solution.js
Used assigning instead comparison in Uppercaserer-server solution.js
> Fixed: Uppercaserer-server solution.js

- CONTRIBUTING.md
Same format as `javascripting`!
> Add documentation on contributing

- exercises/http_json_api_server/problem.md
Change `Date#getTime()` to `Date.getTime()`
> Small typo fix

- exercises/hello_world/exercise.js
> updated hello_world exercise to use const or let instead of var

- exercises/my_first_async_io/exercise.js
> updated my_first_async_io exercise to use const or let instead of var

- exercises/http_file_server/exercise.js
- exercises/http_file_server/problem.es.md
- exercises/http_file_server/problem.fr.md
- exercises/http_file_server/problem.it.md
- exercises/http_file_server/problem.ja.md
- exercises/http_file_server/problem.ko.md
- exercises/http_file_server/problem.md
- exercises/http_file_server/problem.nb-no.md
- exercises/http_file_server/problem.pl.md
- exercises/http_file_server/problem.pt-br.md
- exercises/http_file_server/problem.ru.md
- exercises/http_file_server/problem.uk.md
- exercises/http_file_server/problem.vi.md
- exercises/http_file_server/problem.zh-cn.md
- exercises/http_file_server/problem.zh-tw.md
- test/http_file_server/invalid_02.js
- test/http_file_server/invalid_03.js
- test/http_file_server/valid_01.js
> :wrench: update http_file_server to use onst/let

- README.md
During a node workshopper that was hosted in Vancouver, I found that some of the students would benefit from having a clear set of written instructions on how to complete their first exercise using learnyounode.
I made some changes to the README file by adding step by step instructions on how to complete your first lesson. This will hopefully make learnyounode a bit easier for those that are trying it out on their own.
This is just a first pass, so any suggestions to wording or style would be greatly appreciated!
> Added completing your first exercise section to README.

- i18n/nb-no.json
Fixed minor typographical and grammatical errors for Norwegian-bokmål.
> fix typos and grammatical errors (nb-no)

- test/http_collect/valid_05.js
**Reference:** #639 
Moved `solution_alt.js` as `valid_05.js` to `test/http_collect` directory.
Can confirm `npm run test` executes this test case.
> fix for PR #639

- exercises/http_file_server/problem.fr.md
In french server is a male word, so it's "le serveur".
Thanks for your amazing tutorials.
> Fix typo in french.

- exercises/baby_steps/exercise.js
- exercises/filtered_ls/exercise.js
- exercises/hello_world/exercise.js
- exercises/http_client/exercise.js
- exercises/http_collect/exercise.js
- exercises/http_uppercaserer/exercise.js
- exercises/juggling_async/exercise.js
- exercises/make_it_modular/exercise.js
- exercises/my_first_async_io/exercise.js
- exercises/my_first_io/exercise.js
- lib/words.js
Just refactored some exercise to simplify the setup by using [`workshopper-exercise/basic`](https://github.com/workshopper/workshopper-exercise/blob/master/basic.js)
> refactor: use workshopper-exercise/basic for common exercise setup
